import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Topbar from '@/components/shared/Topbar';
import LeftSidebar from '@/components/shared/LeftSidebar';
import RightSidebar from '@/components/shared/RightSidebar';
import Bottombar from '@/components/shared/Bottombar';
import { Theme } from '@radix-ui/themes';
// import { AuthProvider } from './context/auth';
import { Toaster } from 'sonner';
import { ThemeProvider } from '@/components/theme-provider';
import { QueryProvider } from '@/lib/tanstack-query/QueryProvider';

// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import RightSidebar from "@/components/shared/RightSidebar";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Topbar />
            <main className='flex flex-row container mx-auto max-w-[1280px]'>
              {/* <div className='w-full h-full flex justify-center items-center relative bg-white text-black dark:bg-black dark:text-white'>
              <div className='xl:max-w-[70vw] w-full h-full flex relative'> */}
              <LeftSidebar />
              <section className='flex min-h-screen max-w-[600px] flex-1 flex-col items-center border-x pb-10 max-md:pb-32'>
                <div className='w-full'>{children}</div>
              </section>
              {/* @ts-ignore */}
              <RightSidebar />
            </main>
            <Bottombar />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
