import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import { Theme } from "@radix-ui/themes";
import { AuthProvider } from "./context/auth";
import { NextAuthProvider } from "@/providers/NextAuth";

// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import RightSidebar from "@/components/shared/RightSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <AuthProvider> */}
      <body className={inter.className}>
        <NextAuthProvider>
          <Theme
            accentColor="grass"
            grayColor="sand"
            radius="large"
            scaling="95%"
          >
            <Topbar />
            <main className="flex flex-row">
              <LeftSidebar />
              <section className="main-container">
                <div className="w-full max-w-4xl relative">{children}</div>
              </section>
              {/* @ts-ignore */}
              {/* <RightSidebar /> */}
            </main>
            <Bottombar />
          </Theme>
        </NextAuthProvider>
      </body>
      {/* </AuthProvider> */}
    </html>
  );
}
